import Head from "next/head";
import Image from "next/image";
import React from "react";
import axiosMockInstance from "src/__mock__/config";



export default function Home() {
  React.useEffect(() => {
    const getLogin = async () => {
      const {data} = await axiosMockInstance.get("/users")
      console.log('data',data);
    }
    getLogin()
  },[])
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="#">Anime</a>
        </h1>
      </main>
    </div>
  );
}
